steps:
#step 0 - cat test.txt
- name: 'bash'
  args: ['cat', 'test.txt']
#step 1 - update test.txt
- name: 'bash'
  args: ['-c', 'date +"Touched: %Y-%m-%d %H:%M:%S" >> test.txt']
#step 2 - cat updated test.txt
- name: 'bash'
  args: ['cat', 'test.txt']
#step 3 - push
- name: 'gcr.io/cloud-builders/git'
  args: ['push', 'https://github.com/mikecunliffe/public', 'master']
options:    
    workerPool: 'projects/gdw-dev-smts-pilot/locations/us-central1/workerPools/gdw-dev-smts-pilot-worker-pool'
logsBucket: 'gs://gdw-dev-smts-pilot-default/build-logs'
serviceAccount: 'projects/gdw-dev-smts-pilot/serviceAccounts/shared-service-account@gdw-dev-smts-pilot.iam.gserviceaccount.com'
